<?php
/* --------------------------------------------------------------
   google_shopping.lang.inc.php 2017-11-21
   Gambio GmbH
   http://www.gambio.de
   Copyright (c) 2017 Gambio GmbH
   Released under the GNU General Public License (Version 2)
   [http://www.gnu.org/licenses/gpl-2.0.html]
   --------------------------------------------------------------
*/

$t_language_text_section_content_array = [
    'delete_field_modal_error'                          => 'Die Spalte konnte nicht gelöscht werden.',
    'delete_field_modal_message'                        => 'Möchten Sie diese Spalte wirklich löschen?',
    'delete_field_modal_title'                          => 'Spalte löschen?',
    'delete_scheme_modal_error'                         => 'Das Schema konnte nicht gelöscht werden.',
    'delete_scheme_modal_message'                       => 'Möchten Sie dieses Schema wirklich löschen?',
    'delete_scheme_modal_title'                         => 'Schema löschen?',
    'ERROR_AJAX_FAILED'                                 => 'Es ist ein unbekannter Fehler aufgetreten.',
    'ERROR_EXPORT_AJAX_FAILED'                          => 'Es ist ein unbekannter Fehler während des Exports aufgetreten.',
    'error_invalid_scheme_id'                           => 'Ungültige Schema ID übergeben',
    'error_no_connection_with_google'                   => 'Sie sind nicht mit unserem Google Shopping Service verbunden.',
    'ERROR_SORTING_FAILED'                              => 'Die neue Sortierung der Schema Spalten wurde nicht gespeichert.',
    'ERROR_TITLE'                                       => 'Fehler',
    'export_all_new_categories'                         => 'Alle zuküftig angelegten Kategorien mit exportieren',
    'EXPORT_SCHEME_MODAL_CANCELED'                      => 'Der Export wurde abgebrochen!',
    'EXPORT_SCHEME_MODAL_MESSAGE'                       => 'Bitte warten Sie während Ihr Google Shopping Feed erzeugt wird.',
    'export_scheme_modal_title'                         => 'Exportiere Google Shopping Feed',
    'EXPORT_SCHEME_MODAL_WILL_BE_CANCELED'              => 'Der Export wird abgebrochen ...',
    'field_modal_label_additional_fields'               => 'Zusatzfelder',
    'field_modal_label_attributes'                      => 'Attribute',
    'field_modal_label_default'                         => 'Standardwert',
    'field_modal_label_name'                            => 'Spaltenname',
    'field_modal_label_properties'                      => 'Eigenschaften',
    'field_modal_label_value'                           => 'Spaltenwert',
    'FIELD_MODAL_TITLE_CREATE'                          => 'Spalte hinzufügen',
    'FIELD_MODAL_TITLE_EDIT'                            => 'Spalte bearbeiten',
    'field_modal_variables_collectiv_field'             => 'Kollektivspalte',
    'field_modal_variables_collectiv_field_description' => 'Kollektivspalten dienen der Selektierung von Werten aus verschiedenen Quellen in einer Spalte. Dabei können mehrere Eigenschafts-, Attributs- und/oder Zusatzfeldnamen angegeben werden, aus denen der entsprechende Wert ausgewählt wird. Hinweis: Sollte es für die Selektierung des Spalteninhalts mehrere Treffer aus verschiedenen Quellen geben, so greift eine vorgegebene Priorisierung:Eigenschaften (höchste Priorität), Attribute, Zusatzfelder (niedrigste Priorität)',
    'field_modal_variables_placeholder'                 => 'Verfügbare Variablen',
    'general_label_additional_images'                   => 'Zusätzliche Bilder',
    'general_label_campaign'                            => 'Kampagne',
    'general_label_cronjob_type'                        => 'Modus',
    'general_label_currency'                            => 'Währung',
    'general_label_customers_status'                    => 'Kundengruppe',
    'general_label_export_attributes'                   => 'Attribute exportieren',
    'general_label_export_cronjob'                      => 'Automatischer Export',
    'general_label_export_properties'                   => 'Eigenschaften exportieren',
    'general_label_export_url'                          => 'Export-URL',
    'general_label_cronjob_url'                         => 'Cronjob-URL',
    'general_label_filename'                            => 'Dateiname',
    'general_label_interval'                            => 'Intervall',
    'general_label_language'                            => 'Sprache',
    'general_label_or'                                  => 'oder',
    'general_label_prefer_property_image'               => 'Eigenschaftenbild bevorzugen',
    'general_label_profile_name'                        => 'Profilname',
    'general_label_quantity_minimum'                    => 'Mindestbestand',
    'general_label_quotes'                              => 'Texttrenner',
    'general_label_seperator'                           => 'Trennzeichen',
    'general_label_shipping_free_minimum'               => 'Versandkostenfrei ab',
    'general_label_start_time'                          => 'Startzeit',
    'general_label_weekdays'                            => 'Wochentage',
    'general_no_campaign'                               => 'keine Kampagne',
    'general_tooltip_additional_images'                 => 'Geben Sie hier die maximal Anzahl der Bilder an, die in der Spalte \'Zusätzliche Bilderlinks\' exportiert werden sollen.',
    'general_tooltip_campaign'                          => 'Wählen Sie hier die Kampagne aus, die verwendet werden soll, wenn ein Export dieses Profils erzeugt wird. Hinweis: Kampagnen müssen Sie zunächst unter Konfiguration > Kampagnen anlegen.',
    'general_tooltip_cronjob_type'                      => 'Für den automatischen Export stehen Ihnen zwei Modis bereit. Im Modus \'Startzeit\' wird das Schema einmalig zur konfigurierten Startzeit exportiert. Im Modus \'Intervall\' wird das Schemas mehrmals im konfigurierten zeitlichen Abstand exportiert.',
    'general_tooltip_currency'                          => 'Wählen Sie hier die Währung aus, die verwendet werden soll, wenn ein Export dieses Profils erzeugt wird.',
    'general_tooltip_customers_status'                  => 'Wählen Sie hier die Kundengruppe aus, dessen Preise verwendet werden sollen, wenn ein Export dieses Profils erzeugt wird. Achtung: Wählen Sie \'Gast\' aus, wenn Sie für die gewünschte Kundengruppe nicht in allen Artikeln Kundengruppenpreise hinterlegt haben!',
    'general_tooltip_export_attributes'                 => 'Aktivieren Sie dieses Kontrollkästchen, um Artikelattribute zu berücksichtigen, wenn ein Export dieses Profils erzeugt wird. Hinweis: Attribute werden als eigenständige Artikel exportiert.',
    'general_tooltip_export_cronjob'                    => 'Aktivieren Sie dieses Kontrollkästchen, wenn dieses Export-Profil beim automatischen Export berücksichtigt werden soll. Achtung: Denken Sie daran, den Cronjob für den automatischen Artikelexport bei Ihrem Provider einzurichten!',
    'general_tooltip_export_properties'                 => 'Aktivieren Sie dieses Kontrollkästchen, um Artikeleigenschaften zu berücksichtigen, wenn ein Export dieses Profils erzeugt wird. Hinweis: Eigenschaften-Kombinationen werden als eigenständige Artikel exportiert.',
    'general_tooltip_filename'                          => 'Geben Sie hier den Dateinamen der Export-Datei ein.',
    'general_tooltip_language'                          => 'Wählen Sie hier die zu Sprache aus, die verwendet werden soll, wenn ein Export dieses Profils erzeugt wird.',
    'general_tooltip_prefer_property_image'             => 'Aktivieren Sie dieses Kontrollkästchen, um anstelle des Artikelbildes das Eigenschaftsbild zu exportieren, sofern ein Eigenschaftsbild vorhanden ist.',
    'general_tooltip_profile_name'                      => 'Geben Sie hier den Namen des Export-Profils ein.',
    'general_tooltip_quantity_minimum'                  => 'Geben Sie hier ein, wie oft ein Artikel auf Lager sein muss, damit er beim Export berücksichtigt wird.',
    'general_tooltip_quotes'                            => 'Geben Sie hier den zu verwendenden Texttrenner ein. Lassen Sie das Feld leer für Artikel-Exporte, in denen das Trennzeichen nicht in den Artikelbeschreibungen vorkommt.',
    'general_tooltip_seperator'                         => 'Geben Sie hier das zu verwendende Spalten-Trennzeichen ein. Verwenden Sie die Pipe (|, Senkrechtstrich) für allgemeine Artikelexporte.',
    'general_tooltip_shipping_free_minimum'             => 'Geben Sie hier ein, ab welchem Warenwert Sie Ihre Artikel versandkostenfrei Versenden.',
    'general_tooltip_cronjob_url'                       => 'Geben Sie die hinterlegte Cronjob-URL in einen neuen Cronjob bei Ihrem Provider ein. Ob und wie Cronjobs bei Ihrem Provider eingerichtet werden können, erfragen Sie direkt bei Ihrem Provider. Geben Sie bei Ihrem Provider für den Cronjob einen Ausführungsintervall von 1 Minute an. Mit dem minütlichen Aufruf der Cronjob-URL wird in allen für den Automatikexport konfigurierten Exportvorlagen der hinterlegte Exportintervall überprüft und gegebenenfalls eine Exportdatei erstellt.',
    'general_weekdays_short_friday'                     => 'Fr',
    'general_weekdays_short_monday'                     => 'Mo',
    'general_weekdays_short_saturday'                   => 'Sa',
    'general_weekdays_short_sunday'                     => 'So',
    'general_weekdays_short_thursday'                   => 'Do',
    'general_weekdays_short_tuesday'                    => 'Di',
    'general_weekdays_short_wednesday'                  => 'Mi',
    'heading_export_settings'                           => 'Einstellungen für den automatischen Export',
    'heading_general_settings'                          => 'Allgemeine Einstellungen',
    'last_export'                                       => 'Letzter Export',
    'no_schemes'                                        => 'Keine Daten vorhanden',
    'page_title'                                        => 'Google Shopping Feed',
    'provider'                                          => 'Profilname',
    'select_all'                                        => 'Alle angezeigten Kategorien auswählen / Auswahl aufheben',
    'tab_categories'                                    => 'Kategorien',
    'tab_fields'                                        => 'Artikeldaten',
    'tab_settings'                                      => 'Einstellungen',
    'authorization_success'                             => 'Sie haben ihr Google AdWords-Account erfolgreich mit ihrer Shopsoftware verknüpft'
];
