<?php
/* --------------------------------------------------------------
   google_shopping.lang.inc.php 2017-11-21
   Gambio GmbH
   http://www.gambio.de
   Copyright (c) 2017 Gambio GmbH
   Released under the GNU General Public License (Version 2)
   [http://www.gnu.org/licenses/gpl-2.0.html]
   --------------------------------------------------------------
*/

$t_language_text_section_content_array = [
    'delete_field_modal_error'                          => 'The profile could not be deleted?',
    'delete_field_modal_message'                        => 'Do you really want to delete the profile?',
    'delete_field_modal_title'                          => 'Delete profile?',
    'delete_scheme_modal_error'                         => 'The scheme could not be deleted.',
    'delete_scheme_modal_message'                       => 'Do you really want to delete the profile?',
    'delete_scheme_modal_title'                         => 'Delete profile?',
    'ERROR_AJAX_FAILED'                                 => 'An unexpected error occurred.',
    'ERROR_EXPORT_AJAX_FAILED'                          => 'An unexpected error occurred while exporting.',
    'error_invalid_scheme_id'                           => 'Invalid scheme ID given',
    'error_no_connection_with_google'                   => 'You are not connected with our Google Shopping service.',
    'ERROR_SORTING_FAILED'                              => 'The new sort order for the scheme field could not be saved.',
    'ERROR_TITLE'                                       => 'Error',
    'export_all_new_categories'                         => 'Export all future added categories',
    'EXPORT_SCHEME_MODAL_CANCELED'                      => 'The export has been canceled!',
    'EXPORT_SCHEME_MODAL_MESSAGE'                       => 'Please wait while your Google Shopping feed is being created.',
    'export_scheme_modal_title'                         => 'Exporting Google Shopping Feed',
    'EXPORT_SCHEME_MODAL_WILL_BE_CANCELED'              => 'Going to cancel the export ...',
    'field_modal_label_additional_fields'               => 'Additional fields',
    'field_modal_label_attributes'                      => 'Attributes',
    'field_modal_label_default'                         => 'Default value',
    'field_modal_label_name'                            => 'Field name',
    'field_modal_label_properties'                      => 'Properties',
    'field_modal_label_value'                           => 'Field value',
    'FIELD_MODAL_TITLE_CREATE'                          => 'Add field',
    'FIELD_MODAL_TITLE_EDIT'                            => 'Edit field',
    'field_modal_variables_collectiv_field'             => 'Collective field',
    'field_modal_variables_collectiv_field_description' => 'Collective fields are used to select values from different sources in one column. You can supply multiple names of properties, attributes and additional fields from which the value is selected. Note: If multiple values from different sources are found, the following priorization apllies: Properties (highest priority), Attributes, Additional fields (lowest priority)',
    'field_modal_variables_placeholder'                 => 'Available variables',
    'general_label_additional_images'                   => 'Additional images',
    'general_label_campaign'                            => 'Campaign',
    'general_label_cronjob_type'                        => 'Mode',
    'general_label_currency'                            => 'Currency',
    'general_label_customers_status'                    => 'Customer status',
    'general_label_export_attributes'                   => 'Export attributes',
    'general_label_export_cronjob'                      => 'Automatic export',
    'general_label_export_properties'                   => 'Export properties',
    'general_label_export_url'                          => 'Export-URL',
    'general_label_cronjob_url'                         => 'Cronjob-URL',
    'general_label_filename'                            => 'Filename',
    'general_label_interval'                            => 'Interval',
    'general_label_language'                            => 'Language',
    'general_label_or'                                  => 'or',
    'general_label_prefer_property_image'               => 'Prefer property image',
    'general_label_profile_name'                        => 'Profile name',
    'general_label_quantity_minimum'                    => 'Quantity minimum',
    'general_label_quotes'                              => 'Quotes',
    'general_label_seperator'                           => 'Seperator',
    'general_label_shipping_free_minimum'               => 'Shipping free minimum',
    'general_label_start_time'                          => 'Start time',
    'general_label_weekdays'                            => 'Weekdays',
    'general_no_campaign'                               => 'no campaign',
    'general_tooltip_additional_images'                 => 'Enter here the maximal number ob images, which should be exported in the \'Zusätzliche Bilderlinks\' (additional image URLs) field.',
    'general_tooltip_campaign'                          => 'Select the campaign to be appended to product URLs for this export profile. Notice: You need to add campaigns beforehand at Configuration < Campaigns.',
    'general_tooltip_cronjob_type'                      => 'There are two modes for the automatically export. In the \'Start time\' mode the scheme will be exported only once at the configured start time. In the \'Interval\' mode the scheme will be exported in an time interval of the configured time.',
    'general_tooltip_currency'                          => 'Select the currency to be used when creating export for this export profile.',
    'general_tooltip_customers_status'                  => 'Select the customer group for calculating prices when creating export files for this export profile. Attention: Select \'Guest\' if you do not use customer group prices for this customer group in all products!',
    'general_tooltip_export_attributes'                 => 'Select if you want to include attributes of products when creating export files for this export profile. Notice: Attributes are considered seperate products in the export file.',
    'general_tooltip_export_cronjob'                    => 'Select to include this export profile for the automatic export. Attention: Remember to install the cron job for the automatic product export at your hosting provider!',
    'general_tooltip_export_properties'                 => 'Select if you want to include properties of products when creating export files for this export profile. Notice: Property combinations are considered seperate products in the export file.',
    'general_tooltip_filename'                          => 'Insert the filename of the export file.',
    'general_tooltip_language'                          => 'Select the language to be used when creating export files for this export profile.',
    'general_tooltip_prefer_property_image'             => 'Select if you want to export the property image instead of the product image. This will only be done, if a property image was added.',
    'general_tooltip_profile_name'                      => 'Insert the name of the export profile.',
    'general_tooltip_quantity_minimum'                  => 'Insert the minimum stock required for exporting product details when creating export files for this export profile.',
    'general_tooltip_quotes'                            => 'Insert the text delimiter character. Leave blank for generic product exports, where product descriptions do not contain the field seperator character.',
    'general_tooltip_seperator'                         => 'Insert the field seperator character. Insert the pipe symbol (|, vertical bar) for generic product exports for the highest compatibility towards product descriptions.',
    'general_tooltip_shipping_free_minimum'             => 'Insert the minimum order value, from which you offer free shipping when creating export files for this export profile.',
    'general_tooltip_cronjob_url'                       => 'Create a new cronjob at your hosting provider with this cronjob URL. For information on if and how to create cronjobs please refer to your hosting provider. Configure your new cronjob with a time interval of 1 minute. By calling the cronjob URL every minute, all export presets, that are configured for the automatic export, are checked against their configured time interval and eventually an export file is created.',
    'general_weekdays_short_friday'                     => 'Fri',
    'general_weekdays_short_monday'                     => 'Mon',
    'general_weekdays_short_saturday'                   => 'Sat',
    'general_weekdays_short_sunday'                     => 'Sun',
    'general_weekdays_short_thursday'                   => 'Thu',
    'general_weekdays_short_tuesday'                    => 'Tue',
    'general_weekdays_short_wednesday'                  => 'Wed',
    'heading_export_settings'                           => 'Automatic export settings',
    'heading_general_settings'                          => 'General settings',
    'last_export'                                       => 'Last export',
    'no_schemes'                                        => 'No schemes found',
    'page_title'                                        => 'Google Shopping Feed',
    'provider'                                          => 'Profile name',
    'select_all'                                        => 'Select all displayed categories / Remove selection',
    'tab_categories'                                    => 'Categories',
    'tab_fields'                                        => 'Productdata',
    'tab_settings'                                      => 'Settings',
    'authorization_success'                             => 'You successfully connect your Google AdWords-account with your online shop.'
];